# Generated by Django 2.1 on 2018-11-24 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piezas_indiv',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='productos_gral',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='productos_indiv',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='productos_indiv',
            name='linea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reportes.Lineas'),
        ),
        migrations.AddField(
            model_name='productos_indiv',
            name='resistencia',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
