# Generated by Django 2.1 on 2018-11-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_auto_20181124_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_indiv',
            name='empaque',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
