# Generated by Django 2.1 on 2018-11-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_productos_indiv_empaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_indiv',
            name='fabrica',
            field=models.CharField(choices=[('TIJ', 'Tijuana'), ('ROS', 'Rosarito'), ('TEC', 'Tecate')], default='TIJ', max_length=40),
        ),
    ]
