# Generated by Django 2.1 on 2018-11-25 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_productos_indiv_fabrica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(blank=True, default='sin destino', max_length=40)),
                ('fabrica', models.CharField(choices=[('TIJ', 'Tijuana'), ('ROS', 'Rosarito'), ('TEC', 'Tecate')], default='TIJ', max_length=40)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('linea', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reportes.Lineas')),
            ],
        ),
    ]
