# Generated by Django 2.1 on 2018-11-27 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0007_productos_indiv_piezas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personal', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Cargos')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Sexos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=15)),
                ('contrasena', models.CharField(max_length=15)),
            ],
        ),
    ]
