# Generated by Django 2.1 on 2018-11-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0008_personal_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='producto_pieza',
            name='pieza',
        ),
        migrations.RemoveField(
            model_name='producto_pieza',
            name='producto',
        ),
        migrations.AddField(
            model_name='lotes',
            name='productos',
            field=models.ManyToManyField(blank=True, to='reportes.Productos_indiv'),
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
        migrations.DeleteModel(
            name='Producto_pieza',
        ),
    ]
