# Generated by Django 2.1 on 2018-11-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_auto_20181128_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='productos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'estado': True}, to='reportes.Productos_indiv'),
        ),
    ]
