# Generated by Django 2.1 on 2018-11-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0010_auto_20181129_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='productos',
            field=models.ManyToManyField(blank=True, to='reportes.Productos_indiv'),
        ),
    ]
