# Generated by Django 2.1 on 2018-11-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0012_productos_indiv_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos_indiv',
            name='prueba',
        ),
        migrations.AddField(
            model_name='orden_almacen',
            name='piezas',
            field=models.ManyToManyField(blank=True, to='reportes.Piezas_indiv'),
        ),
    ]
