# Generated by Django 2.1 on 2018-11-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0013_auto_20181130_0740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargos',
        ),
        migrations.RemoveField(
            model_name='pieza_orden',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='pieza_orden',
            name='pieza',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Pieza_orden',
        ),
    ]
