# Generated by Django 2.1 on 2018-12-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0014_auto_20181130_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_indiv',
            name='prueba',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
