# Generated by Django 2.1 on 2018-12-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0015_productos_indiv_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos_indiv',
            name='prueba',
        ),
    ]
