# Generated by Django 2.1 on 2018-12-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0016_remove_productos_indiv_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_indiv',
            name='prueba',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
