# Generated by Django 2.1 on 2018-12-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0017_productos_indiv_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_indiv',
            name='prueba_estado',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
