# Generated by Django 2.1 on 2018-12-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0018_productos_indiv_prueba_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='productos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'prueba_estado': 'aprobado'}, to='reportes.Productos_indiv'),
        ),
    ]
